title: GitHub Explore Feed
description: Feed for GitHub Topics and Collections.

plugins:
  - jekyll-redirect-from

exclude:
  - .git
  - CNAME
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - collections
  - topics
  - test

collections:
  topics:
  explore_collections:
