name: Check for conflicts of interest

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          In order to review it for acceptance, we need to make sure that all of the prerequisites are satisfied.

          This was not checked:

          > I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee)

          This is a requirement to maintain a high level of independence in this project.

          Please reopen this PR and update appropriately if you are able to verify that you meet that requirement.

          Thank you!
