name: Check for conflicts of interest

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, '- [ ] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).')
    steps:
      - uses: actions/checkout@v3

      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: templates/conflict.md
