name: Build and Publish Jekyll for GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 setup
      uses: actions/checkout@v3

    - name: 💎 setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: 🔨 install dependencies & build site
      uses: actions/jekyll-build-pages@v1.0.6
        
    - name: 🚀 deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
