name: Build and Publish Jekyll for GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 setup
      uses: actions/checkout@v3

    - name: 💎 setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: 🔨 install dependencies & build site
      uses: actions/jekyll-build-pages@v1.0.6

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 🚀 deploy
        id: deployment
        uses: actions/deploy-pages@v1.2.3
